---

- name: Show status of Zpool from primary storages
  hosts: primarystorages
  gather_facts: false
  tasks:

  - name: check primary storages zpool status
    shell:
      cmd: zpool status | grep "pool\|state"
    register: command_output

  - debug:
      var: command_output.stdout_lines
